### Site Settings ###
title               : Wegrowski's data blog
description         : >-
                      Ph.D. in Mechanical Engineering from 9 to 5,
                      Data Scientist after 5
                      and on the weekends too.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Rufski/Rufski.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Antoine Wegrowski
  image             : images/Profile pic.jpg
  email             : awegrows@gmail.com
  github            : Rufski
  linkedin          : wegrowski


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
  - scope:
      path: "https://www.linkedin.com/in/wegrowski/"
      type: "LinkedIn"
  - scope:
      path: "http://github.com/rufski/"
      type: "GitHub"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
